apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-11-16T16:38:56Z"
  generation: 1
  labels:
    app: ionic-app
  name: ionic-app
  namespace: project
  resourceVersion: "267370"
  uid: 3263741e-9e12-4bc1-ab74-ed11bc6fc5f3
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ionic-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ionic-app
    spec:
      containers:
      - image: malikdevops/ionic-project
        imagePullPolicy: Always
        name: ionic-project
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-11-16T16:40:03Z"
    lastUpdateTime: "2023-11-16T16:40:03Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-11-16T16:38:56Z"
    lastUpdateTime: "2023-11-16T16:40:03Z"
    message: ReplicaSet "ionic-app-666986449f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
